version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/mongo-data/:/data/db
    enviroment:
      MONGO_INTDB_ROOT_USERNAME: ${MONGO_INTDB_ROOT_USERNAME}
      MONGO_INTDB_ROOT_PASSWORD: ${MONGO_INTDB_ROOT_PASSWORD}

  mongo-express:
  image: mongo-express
  restart: always
  ports:
    - 8001:8001
  depends_on:
    - mongo
  enviroment:
  ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INTDB_ROOT_USERNAME}
  ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INTDB_ROOT_PASSWORD}
